# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58eadbd283683a6ba88b850ae0100580ede75969a10acf5817a17a6c81b3cc192957bda1873f0fd09a478544b1b7847c64a7a219f4e0687c0f3283422bc9fc76

test:
  secret_key_base: 1a914f2c3ed3642bfa8854fb545523d5111d819562760935dd82fd2547dfe34b4919b67e91926c8797314182a3f140a66264de75981e4df02461f0f014734a5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
